spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari
      maximum-pool-size: 30
      connection-timeout: 30000
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 10MB

server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework: INFO
    com.ifengxue: INFO
swagger:
  enabled: false
todolist:
  token:
    validPeriod: 20 # token有效期，单位分钟