spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: developer
    password: developer
swagger:
  enabled: true
  title: ToDoList
  description: 项目进度管理
  version: 1.0.0
  contact:
    name: 刘克峰
    url: https://www.ifengxue.com
    email: liukefeng2008@hotmail.com
  base-package: com.ifengxue.todolist.web